#!/usr/bin/env bash

# Ensure this file is executable via chmod a+x bill, then place it
# somewhere on your $PATH, like ~/bin. The rest of Bill the Builder will be
# installed upon first run into the ~/.bill/self-installs directory.

export BILL_VERSION="0.0.1"

case $BILL_VERSION in
    *SNAPSHOT) SNAPSHOT="YES" ;;
    *) SNAPSHOT="NO" ;;
esac

if [ `id -u` -eq 0 ] && [ "$BILL_ROOT" = "" ]; then
    echo "WARNING: You're currently running as root; probably by accident."
    echo "Press control-C to abort or Enter to continue as root."
    echo "Set BILL_ROOT to disable this warning."
    read _
fi

NOT_FOUND=1
ORIGINAL_PWD="$PWD"
while [ ! -r "$PWD/build.clj" ] && [ "$PWD" != "/" ] && [ $NOT_FOUND -ne 0 ]
do
    cd ..
    if [ "$(dirname "$PWD")" = "/" ]; then
        NOT_FOUND=0
        cd "$ORIGINAL_PWD"
    fi
done

export BILL_HOME=${BILL_HOME:-"$HOME/.lein"}

for f in "$BILL_HOME/billrc" ".billrc"; do
  if [ -e $f ]; then
    source $f
  fi
done

if [ "$OSTYPE" = "cygwin" ]; then
    export BILL_HOME=`cygpath -w $BILL_HOME`
fi

BILL_JAR="$BILL_HOME/self-installs/bill-$BILL_VERSION-standalone.jar"

# normalize $0 on certain BSDs
if [ "$(dirname "$0")" = "." ]; then
    SCRIPT="$(which $(basename "$0"))"
else
    SCRIPT="$0"
fi

# resolve symlinks to the script itself portably
while [ -h "$SCRIPT" ] ; do
    ls=`ls -ld "$SCRIPT"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        SCRIPT="$link"
    else
        SCRIPT="$(dirname "$SCRIPT"$)/$link"
    fi
done

BIN_DIR="$(dirname "$SCRIPT")"

# Try to make the default more sane for :eval-in :classloader.lein
grep -E -q '^\s*:eval-in\s+:classloader\s*$' build.clj 2> /dev/null &&
BILL_JVM_OPTS=${BILL_JVM_OPTS:-'-Xms64m -Xmx512m'}

if [ -f .bill-classpath ]; then
    CLASSPATH="`cat .bill-classpath`:$BILL_JAR"
else
    CLASSPATH="$BILL_JAR"
fi

export BILL_JVM_OPTS=${BILL_JVM_OPTS:-"-Xbootclasspath/a:$BILL_JAR"}

if [ ! -r "$BILL_JAR" -a "$1" != "self-install" ]; then
    "$0" self-install
fi

if [ "$HTTP_CLIENT" = "" ]; then
    if type -p curl >/dev/null 2>&1; then
        if [ "$https_proxy" != "" ]; then
            CURL_PROXY="-x $https_proxy"
        fi
        HTTP_CLIENT="curl $CURL_PROXY -f -L -o"
    else
        HTTP_CLIENT="wget -O"
    fi
fi

function download_failed_message {
    echo "Failed to download $1"
    echo "It's possible your HTTP client's certificate store does not have the"
    echo "correct certificate authority needed. This is often caused by an"
    echo "out-of-date version of libssl. Either upgrade it or set HTTP_CLIENT"
    echo "to turn off certificate checks:"
    echo "  export HTTP_CLIENT=\"wget --no-check-certificate -O\" # or"
    echo "  export HTTP_CLIENT=\"curl --insecure -f -L -o\""
}

# TODO: explain what to do when Java is missing
export JAVA_CMD=${JAVA_CMD:-"java"}
export BILL_JAVA_CMD=${BILL_JAVA_CMD:-$JAVA_CMD}

# Support $JAVA_OPTS for backwards-compatibility.
export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"

# TODO: investigate http://skife.org/java/unix/2011/06/20/really_executable_jars.html
# If you're packaging this for a package manager (.deb, homebrew, etc)
# you need to remove the self-install and upgrade functionality or see lein-pkg.
if [ "$1" = "self-install" ]; then
    if [ -r "$BILL_JAR" ]; then
      echo "The self-install jar already exists at $BILL_JAR."
      echo "If you wish to re-download, delete it and rerun \"$0 self-install\"."
      exit 1
    fi
    echo "Downloading Bill the Builder now..."
    BILL_DIR=`dirname "$BILL_JAR"`
    mkdir -p "$BILL_DIR"
    BILL_URL="https://github.com/downloads/macourtney/bill/bill-$BILL_VERSION-standalone.jar"
    $HTTP_CLIENT "$BILL_JAR.pending" "$BILL_URL"
    if [ $? == 0 ]; then
        # TODO: checksum
        mv -f "$BILL_JAR.pending" "$BILL_JAR"
    else
        rm "$BILL_JAR.pending" 2> /dev/null
        download_failed_message "$BILL_URL"
        if [ $SNAPSHOT = "YES" ]; then
            echo "See README.md for SNAPSHOT-specific build instructions."
        fi
        exit 1
    fi
elif [ "$1" = "upgrade" ]; then
    if [ "$BILL_DIR" != "" ]; then
        echo "The upgrade task is not meant to be run from a checkout."
        exit 1
    fi
    if [ $SNAPSHOT = "YES" ]; then
        echo "The upgrade task is only meant for stable releases."
        echo "See the \"Hacking\" section of the README."
        exit 1
    fi
    if [ ! -w "$SCRIPT" ]; then
        echo "You do not have permission to upgrade the installation in $SCRIPT"
        exit 1
    else
        TARGET_VERSION="${2:-"preview"}"
        echo "The script at $SCRIPT will be upgraded to the latest $TARGET_VERSION version."
        echo -n "Do you want to continue [Y/n]? "
        read RESP
        case "$RESP" in
            y|Y|"")
                echo
                echo "Upgrading..."
                TARGET="/tmp/bill-$$-upgrade"
                if [ "$OSTYPE" = "cygwin" ]; then
                    TARGET=`cygpath -w $TARGET`
                fi
                BILL_SCRIPT_URL="https://github.com/macourtney/bill/raw/$TARGET_VERSION/bin/bill"
                $HTTP_CLIENT "$TARGET" "$BILL_SCRIPT_URL"
                if [ $? == 0 ]; then
                    mv "$TARGET" "$SCRIPT" \
                        && chmod +x "$SCRIPT" \
                        && echo && "$SCRIPT" self-install \
                        && echo && echo "Now running" `$SCRIPT version`
                    exit $?
                else
                    download_failed_message "$BILL_SCRIPT_URL"
                fi;;
            *)
                echo "Aborted."
                exit 1;;
        esac
    fi
else
    if [ "$OSTYPE" = "cygwin" ]; then
        # When running on Cygwin, use Windows-style paths for java
        ORIGINAL_PWD=`cygpath -w "$ORIGINAL_PWD"`
        CLASSPATH=`cygpath -wp "$CLASSPATH"`
    fi

    if [ $DEBUG ]; then
        echo "Bill the Builder's classpath: $CLASSPATH"
    fi

    if [ "$BILL_FAST_TRAMPOLINE" = "" ] && [ ! -r .lein-fast-trampoline ]; then
        TRAMPOLINE_FILE="/tmp/BILL-trampoline-$$"
        trap "rm -f $TRAMPOLINE_FILE" EXIT
    else
        INPUTS="$@ $(cat build.clj) $(cat $BILL_HOME/profiles.clj)"
        INPUT_CHECKSUM=$(echo $INPUTS | shasum - | cut -f 1 -d " ")
        # Just don't change :target-path in build.clj, mkay?
        TRAMPOLINE_FILE="target/trampolines/$INPUT_CHECKSUM"
    fi

    if [ "$OSTYPE" = "cygwin" ]; then
        TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
    fi

    if [ "$INPUT_CHECKSUM" != "" ] && [ -r "$TRAMPOLINE_FILE" ]; then
        if [ $DEBUG ]; then
            echo "Fast trampoline with $TRAMPOLINE_FILE."
        fi
        exec sh -c "exec $(cat $TRAMPOLINE_FILE)"
    else
        $BILL_JAVA_CMD \
            -client -XX:+TieredCompilation \
            $BILL_JVM_OPTS \
            -Dfile.encoding=UTF-8 \
            -Dmaven.wagon.http.ssl.easy=false \
            -Dbill.original.pwd="$ORIGINAL_PWD" \
            -Dbill.trampoline-file="$TRAMPOLINE_FILE" \
            -cp "$CLASSPATH" \
            clojure.main -m bill.core.main "$@"

        EXIT_CODE=$?

        if [ -r "$TRAMPOLINE_FILE" ]; then
            TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
            if [ "$INPUT_CHECKSUM" = "" ]; then
                rm $TRAMPOLINE_FILE
            fi
            exec sh -c "exec $TRAMPOLINE"
        else
            exit $EXIT_CODE
        fi
    fi
fi
